services:
  web:
    build: .
    ports:
      - "3000:3000"
  cypress:
    image: "cypress/included:latest"
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:3000
    working_dir: /e2e
    volumes:
      - ./:/e2e
